### PR TITLE
Bump to Spring Boot 2

### PR DESCRIPTION
**Pull request by mjlodge**
This change bumps up the Spring Boot version to 2. There's a change to the Spring Data API so code now uses findById() instead of findOne().

### CODE REVIEW

**Comment by mjlodge** [comment]
Error seems to be in creds for Docker -- don't know how to fix that

**Comment by dholbach** [comment]
Hi @mjlodge - thanks for the PR.

I'm not a Java expert - far from it, but wouldn't we want to change these instances too?

```console
[daniel@reef carts ]$ git grep -i "jdk.*8"
Dockerfile:FROM java:openjdk-8-alpine
scripts/build.sh:$DOCKER_CMD run --rm -v $HOME/.m2:/root/.m2 -v $CODE_DIR:/usr/src/mymaven -w /usr/src/mymaven maven:3.2-jdk-8 mvn -q -DskipTests package
test/component.py:                   '/usr/src/mymaven', 'maven:3.2-jdk-8', 'mvn', 'integration-test']
test/coveralls.py:                   'maven:3.2-jdk-8',
test/unit.py:                   '/usr/src/mymaven', 'maven:3.2-jdk-8', 'mvn', '-q', 'test']
[daniel@reef carts ]$ 
```

**Comment by richardcase** [comment]
Thanks @mjlodge - LTGM. 

It probably is a good idea to update the maven docker image as well to jdk 11 as @dholbach mentions. What do you think?

**Comment by mjlodge** [comment]
Bumped Maven test container to 3.6/JDK 11.

**Comment by mjlodge** [comment]
Says merging is still blocked. Someone with write access needs to approve.

**Comment by dholbach** [comment]
@jpellizzari @philwinder Can one of you merge this?

**Comment by dholbach** [comment]
Looks like CI is unhappy: https://travis-ci.org/github/microservices-demo/carts/builds/712117698

```
$ docker login -u $DOCKER_USER -p $DOCKER_PASS;
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
```

**Comment by mjlodge** [comment]
This is something only you can fix -- how do you want to do Docker auth?

The way the script was set up, all non-Weaveworks commits would fail CI. So I restored the previous script, which has this line in it -- which is just for you (Weaveworks) to push new images to Dockerhub.

**Pull request merged**
